import React from 'react'
import './TestimonialsSection.css'
function TestimonialsSection() {
  return (
<div class="testimonials-section">
    <h2>Testimonials</h2>
    
    <div class="testimonial-card">
        <div class="testimonial-photo">
            <img src="path-to-photo/john-doe.jpg" alt="John Doe"/>
        </div>
        <div class="testimonial-content">
            <p>"MeetingMind transformed how we handle meetings. The AI summaries are spot on!"</p>
            <p class="testimonial-name">- John Doe, CEO of XYZ Corp.</p>
        </div>
    </div>

    <div class="testimonial-card">
        <div class="testimonial-photo">
            <img src="path-to-photo/jane-smith.jpg" alt="Jane Smith"/>
        </div>
        <div class="testimonial-content">
            <p>"The action items generated by MeetingMind have streamlined our project management."</p>
            <p class="testimonial-name">- Jane Smith, Project Manager at ABC Co.</p>
        </div>
    </div>

    <div class="testimonial-card">
        <div class="testimonial-photo">
            <img src="path-to-photo/mark-wilson.jpg" alt="Mark Wilson"/>
        </div>
        <div class="testimonial-content">
            <p>"We no longer miss important details from our meetings, thanks to MeetingMind's AI."</p>
            <p class="testimonial-name">- Mark Wilson, Director at DEF Ltd.</p>
        </div>
    </div>
</div>
  )
}

export default TestimonialsSection